# Generated by Django 5.0.3 on 2024-05-22 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Цвет')),
                ('code', models.CharField(max_length=200, verbose_name='RGB код')),
                ('bcor', models.PositiveIntegerField(verbose_name='Коор1')),
                ('gcor', models.PositiveIntegerField(verbose_name='Коор2')),
                ('rcor', models.PositiveIntegerField(verbose_name='Коор3')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.TextField(verbose_name='Фото')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фотография из поста ВК',
                'verbose_name_plural': 'Фотографии (пост ВК)',
            },
        ),
        migrations.CreateModel(
            name='PartFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_part_face', models.CharField(max_length=50, verbose_name='Часть лица')),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='demo.posts', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Часть лица фотографии поста',
                'verbose_name_plural': 'Части лица (пост ВК)',
            },
        ),
        migrations.CreateModel(
            name='Shades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcor_photo', models.PositiveIntegerField(verbose_name='Коор1_фото')),
                ('gcor_photo', models.PositiveIntegerField(verbose_name='Коор2_фото')),
                ('rcor_photo', models.PositiveIntegerField(verbose_name='Коор3_фото')),
                ('part_face', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.partface')),
            ],
            options={
                'verbose_name': 'Оттенок части лица (пост ВК)',
                'verbose_name_plural': 'Оттенки части лица (пост ВК)',
            },
        ),
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.TextField(verbose_name='Фото')),
                ('user_image_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Фотография пользователя',
                'verbose_name_plural': 'Фотографии (пользователь)',
            },
        ),
        migrations.CreateModel(
            name='UserPartFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_part_face', models.CharField(max_length=50, verbose_name='Часть лица')),
                ('user_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='demo.userimages', verbose_name='Фото пользователя')),
            ],
            options={
                'verbose_name': 'Часть лица пользователя',
                'verbose_name_plural': 'Части лица (пользователь)',
            },
        ),
        migrations.CreateModel(
            name='UserShades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_shade', models.CharField(max_length=100, verbose_name='Оттенок')),
                ('user_part_face', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='us_partface', to='demo.userpartface', verbose_name='Часть лица пользователя')),
            ],
            options={
                'verbose_name': 'Оттенок части лица пользователя',
                'verbose_name_plural': 'Оттенки части лица (пользователь)',
            },
        ),
    ]
