# Generated by Django 5.0.3 on 2024-05-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.CharField(max_length=200, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='user_image',
            field=models.CharField(verbose_name='Фото'),
        ),
    ]
