# Generated by Django 5.0.3 on 2024-05-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alter_posts_post_image_alter_userimages_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershades',
            name='user_shade',
        ),
        migrations.AddField(
            model_name='usershades',
            name='bcor_user_photo',
            field=models.PositiveIntegerField(default=None, verbose_name='Коор1_фото_пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usershades',
            name='gcor_user_photo',
            field=models.PositiveIntegerField(default=None, verbose_name='Коор2_фото_пользователя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usershades',
            name='rcor_user_photo',
            field=models.PositiveIntegerField(default=None, verbose_name='Коор3_фото_пользователя'),
            preserve_default=False,
        ),
    ]
